### ISSUE TITLE
sso login in sogo don't work

### ISSUE THREAD

**Issue by luckycloud-GmbH** [fsphys/sogo-keycloak-docker-example#2]
Hi,

I have installed the setup according to the instructions in README.md.

I had to change the URL of Sogo, but after that everything could be installed.
When I log in to Sogo, however, I get an error message.
I can log in to Keycloak with the user, but during the redirect in the login phase to http://localhost:9090/SOGo/saml2-signon-post I get the following error message
HTTP ERROR 501

**Comment by AlexanderKaschta** [comment]
This repository was used to report a SAML bug with the SOGo developers. I don't know, if the bugs were fixed by the developers, but we did not look further in the SAML setup. In addition, the `Dockerfile` is deprecated and no longer safe to use, as it missing crucial updates.
